config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :category_posts

  resources :categories

  resources :posts

  resources :users

	root :to => "posts#index"
end

app/models/category_post.rb
class CategoryPost < ActiveRecord::Base
	belongs_to :post	#принадлежит посту
	belongs_to :category	#принадлежит категориям
end

app/controllers/category_posts_controller.rb
class CategoryPostsController < ApplicationController
  # GET /category_posts
  # GET /category_posts.xml
  def index
    @category_posts = CategoryPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @category_posts }
    end
  end

  # GET /category_posts/1
  # GET /category_posts/1.xml
  def show
    @category_post = CategoryPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category_post }
    end
  end

  # GET /category_posts/new
  # GET /category_posts/new.xml
  def new
    @category_post = CategoryPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category_post }
    end
  end

  # GET /category_posts/1/edit
  def edit
    @category_post = CategoryPost.find(params[:id])
  end

  # POST /category_posts
  # POST /category_posts.xml
  def create
    @category_post = CategoryPost.new(params[:category_post])

    respond_to do |format|
      if @category_post.save
        format.html { redirect_to(@category_post, :notice => 'Category post was successfully created.') }
        format.xml  { render :xml => @category_post, :status => :created, :location => @category_post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /category_posts/1
  # PUT /category_posts/1.xml
  def update
    @category_post = CategoryPost.find(params[:id])

    respond_to do |format|
      if @category_post.update_attributes(params[:category_post])
        format.html { redirect_to(@category_post, :notice => 'Category post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /category_posts/1
  # DELETE /category_posts/1.xml
  def destroy
    @category_post = CategoryPost.find(params[:id])
    @category_post.destroy

    respond_to do |format|
      format.html { redirect_to(category_posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/category_posts_helper.rb
module CategoryPostsHelper
end

app/views/category_posts/_form.html.erb
<%= form_for(@category_post) do |f| %>
  <% if @category_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category_post.errors.count, "error") %> prohibited this category_post from being saved:</h2>

      <ul>
      <% @category_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/category_posts/edit.html.erb
<h1>Editing category_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @category_post %> |
<%= link_to 'Back', category_posts_path %>

app/views/category_posts/index.html.erb
<h1>Listing category_posts</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @category_posts.each do |category_post| %>
  <tr>
    <td><%= category_post.post_id %></td>
    <td><%= category_post.category_id %></td>
    <td><%= link_to 'Show', category_post %></td>
    <td><%= link_to 'Edit', edit_category_post_path(category_post) %></td>
    <td><%= link_to 'Destroy', category_post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category post', new_category_post_path %>

app/views/category_posts/new.html.erb
<h1>New category_post</h1>

<%= render 'form' %>

<%= link_to 'Back', category_posts_path %>

app/views/category_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @category_post.post_id %>
</p>

<p>
  <b>Category:</b>
  <%= @category_post.category_id %>
</p>


<%= link_to 'Edit', edit_category_post_path(@category_post) %> |
<%= link_to 'Back', category_posts_path %>